### ISSUE TITLE
using Arctron.Obj23dTiles

### ISSUE THREAD

**Issue by simonasdmd** [arcplus/ObjConvert#1]
Hello, I downloaded the source package, but when I compile, the compiler prompts for a lot of references. Similar to the namespace Arctron does not exist Obj23dTiles. Or does not find GisPosition and the like. What should I do? Looking forward to your reply

**Comment by simonasdmd** [comment]
hi~ 
Is there any idea about this issue now?

**Comment by simonasdmd** [comment]
@stoneflyop1 
hi~
How to split the OBJ file. I mean to split an obj file into many small obj files.

**Comment by stoneflyop1** [comment]
hi, @simonasdmd 
first you get an ObjModel from ObjParser, then you can call ObjModel.Split method to split.
